/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ExecutionResponse : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ExecutionResponse(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ExecutionResponse obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ExecutionResponse() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ContextModulePINVOKE.delete_ExecutionResponse(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ExecutionResponse() : this(ContextModulePINVOKE.new_ExecutionResponse__SWIG_0(), true) {
  }

  public ExecutionResponse(string buf) : this(ContextModulePINVOKE.new_ExecutionResponse__SWIG_1(buf), true) {
  }

  public void dump() {
    ContextModulePINVOKE.ExecutionResponse_dump(swigCPtr);
  }

  public ulong getClOrderId() {
    ulong ret = ContextModulePINVOKE.ExecutionResponse_getClOrderId(swigCPtr);
    return ret;
  }

  public byte getTransactionType() {
    byte ret = ContextModulePINVOKE.ExecutionResponse_getTransactionType(swigCPtr);
    return ret;
  }

  public byte getResponseType() {
    byte ret = ContextModulePINVOKE.ExecutionResponse_getResponseType(swigCPtr);
    return ret;
  }

  public uint getTokenId() {
    uint ret = ContextModulePINVOKE.ExecutionResponse_getTokenId(swigCPtr);
    return ret;
  }

  public void setClOrderId(ulong clOrderId) {
    ContextModulePINVOKE.ExecutionResponse_setClOrderId(swigCPtr, clOrderId);
  }

  public void setTransactionType(byte transactionType) {
    ContextModulePINVOKE.ExecutionResponse_setTransactionType(swigCPtr, transactionType);
  }

  public void setResponseType(byte responseType) {
    ContextModulePINVOKE.ExecutionResponse_setResponseType(swigCPtr, responseType);
  }

  public void setTokenId(uint val) {
    ContextModulePINVOKE.ExecutionResponse_setTokenId(swigCPtr, val);
  }

}
