/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum OrderStatus {
  OrderStatus_PENDING,
  OrderStatus_CONFIRMED,
  OrderStatus_FILLED,
  OrderStatus_CANCELED,
  OrderStatus_REPLACED,
  OrderStatus_NEW_REJECTED,
  OrderStatus_CANCEL_REJECTED,
  OrderStatus_REPLACE_REJECTED,
  OrderStatus_FROZEN,
  OrderStatus_MARKET_TO_LIMIT,
  OrderStatus_TRIGGERED,
  OrderStatus_PARTIALLY_FILLED,
  OrderStatus_CANCELED_OF_IOC,
  OrderStatus_RMS_REJECT,
  OrderStatus_MAX
}
