/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum OrderType {
  OrderType_LIMIT,
  OrderType_MARKET,
  OrderType_STOP_LIMIT,
  OrderType_STOP,
  OrderType_MAX
}
