/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class OrderBook : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OrderBook(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OrderBook obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OrderBook() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ContextModulePINVOKE.delete_OrderBook(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Order getOrder(long clOrderId) {
    IntPtr cPtr = ContextModulePINVOKE.OrderBook_getOrder(swigCPtr, clOrderId);
    Order ret = (cPtr == IntPtr.Zero) ? null : new Order(cPtr, false);
    if (ContextModulePINVOKE.SWIGPendingException.Pending) throw ContextModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int update(ExecutionReport report, bool reconcileOldOrders) {
    int ret = ContextModulePINVOKE.OrderBook_update__SWIG_0(swigCPtr, ExecutionReport.getCPtr(report), reconcileOldOrders);
    if (ContextModulePINVOKE.SWIGPendingException.Pending) throw ContextModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int update(ExecutionReport report) {
    int ret = ContextModulePINVOKE.OrderBook_update__SWIG_1(swigCPtr, ExecutionReport.getCPtr(report));
    if (ContextModulePINVOKE.SWIGPendingException.Pending) throw ContextModulePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void insert(Order order) {
    ContextModulePINVOKE.OrderBook_insert(swigCPtr, Order.getCPtr(order));
  }

  public OrderBook() : this(ContextModulePINVOKE.new_OrderBook(), true) {
  }

}
