/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Portfolio : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Portfolio(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Portfolio obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Portfolio() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ContextModulePINVOKE.delete_Portfolio(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public static Portfolio getInstance() {
    IntPtr cPtr = ContextModulePINVOKE.Portfolio_getInstance();
    Portfolio ret = (cPtr == IntPtr.Zero) ? null : new Portfolio(cPtr, false);
    return ret;
  }

  public void insert(Order order) {
    ContextModulePINVOKE.Portfolio_insert(swigCPtr, Order.getCPtr(order));
  }

  public Order getOrderByTokenId(int tokenId) {
    IntPtr cPtr = ContextModulePINVOKE.Portfolio_getOrderByTokenId(swigCPtr, tokenId);
    Order ret = (cPtr == IntPtr.Zero) ? null : new Order(cPtr, false);
    return ret;
  }

  public NetPositions getNetPositions() {
    NetPositions ret = new NetPositions(ContextModulePINVOKE.Portfolio_getNetPositions(swigCPtr), false);
    return ret;
  }

  public OrderBook getOrderBook() {
    OrderBook ret = new OrderBook(ContextModulePINVOKE.Portfolio_getOrderBook(swigCPtr), false);
    return ret;
  }

  public TradeBook getTradeBook() {
    TradeBook ret = new TradeBook(ContextModulePINVOKE.Portfolio_getTradeBook(swigCPtr), false);
    return ret;
  }

}
