/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ResponseType {
  ResponseType_SUCCESS,
  ResponseType_FAILURE,
  ResponseType_TERMINATE_SUCCESS,
  ResponseType_TERMINATE_FAILURE,
  ResponseType_TERMINATE_SQUAREOFF_SUCCESS,
  ResponseType_TERMINATE_SQUAREOFF_FAILURE,
  ResponseType_PAUSE_STRATEGY_SUCCESS,
  ResponseType_PAUSE_STRATEGY_FAILURE,
  ResponseType_STRATEGY_RUNNING,
  ResponseType_TERMINATE_SPREAD_BREACHED,
  ResponseType_ALGO_NOT_ALLOWED,
  ResponseType_MAX
}
