/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum Side {
  Side_BUY = 0,
  Side_SELL = 1,
  Side_BID = 0,
  Side_ASK = 1
}
