/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AbstractLogger {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AbstractLogger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AbstractLogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_AbstractLogger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ContextModeuleJNI.AbstractLogger_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ContextModeuleJNI.AbstractLogger_change_ownership(this, swigCPtr, true);
  }

  public void log(LogLevel level, String message) {
    ContextModeuleJNI.AbstractLogger_log(swigCPtr, this, level.swigValue(), message);
  }

  public int getLevel(LogLevel level) {
    return ContextModeuleJNI.AbstractLogger_getLevel(swigCPtr, this, level.swigValue());
  }

  public void setLogLevel(LogLevel level) {
    ContextModeuleJNI.AbstractLogger_setLogLevel(swigCPtr, this, level.swigValue());
  }

  public int getLogLevel() {
    return ContextModeuleJNI.AbstractLogger_getLogLevel(swigCPtr, this);
  }

  public AbstractLogger() {
    this(ContextModeuleJNI.new_AbstractLogger(), true);
    ContextModeuleJNI.AbstractLogger_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
