/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Application {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Application(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Application obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Application(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ContextModeuleJNI.Application_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ContextModeuleJNI.Application_change_ownership(this, swigCPtr, true);
  }

  public void onTick(MarketData arg0) {
    if (getClass() == Application.class) ContextModeuleJNI.Application_onTick(swigCPtr, this, MarketData.getCPtr(arg0), arg0); else ContextModeuleJNI.Application_onTickSwigExplicitApplication(swigCPtr, this, MarketData.getCPtr(arg0), arg0);
  }

  public void onLogin(boolean status) {
    if (getClass() == Application.class) ContextModeuleJNI.Application_onLogin(swigCPtr, this, status); else ContextModeuleJNI.Application_onLoginSwigExplicitApplication(swigCPtr, this, status);
  }

  public void onLogout(boolean status) {
    if (getClass() == Application.class) ContextModeuleJNI.Application_onLogout(swigCPtr, this, status); else ContextModeuleJNI.Application_onLogoutSwigExplicitApplication(swigCPtr, this, status);
  }

  public void onExecutionReport(ExecutionReport report) {
    if (getClass() == Application.class) ContextModeuleJNI.Application_onExecutionReport(swigCPtr, this, ExecutionReport.getCPtr(report), report); else ContextModeuleJNI.Application_onExecutionReportSwigExplicitApplication(swigCPtr, this, ExecutionReport.getCPtr(report), report);
  }

  public void onLoadInstrumentEnd(String instrumentName, boolean success) {
    if (getClass() == Application.class) ContextModeuleJNI.Application_onLoadInstrumentEnd(swigCPtr, this, instrumentName, success); else ContextModeuleJNI.Application_onLoadInstrumentEndSwigExplicitApplication(swigCPtr, this, instrumentName, success);
  }

  public Application() {
    this(ContextModeuleJNI.new_Application(), true);
    ContextModeuleJNI.Application_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
