/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Context {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void login(int userId, String password, String host, short port, boolean restoreState) {
    ContextModeuleJNI.Context_login__SWIG_0(swigCPtr, this, userId, password, host, port, restoreState);
  }

  public void login(int userId, String password, String host, short port) {
    ContextModeuleJNI.Context_login__SWIG_1(swigCPtr, this, userId, password, host, port);
  }

  public void logout() {
    ContextModeuleJNI.Context_logout(swigCPtr, this);
  }

  public boolean placeOrder(Order order) {
    return ContextModeuleJNI.Context_placeOrder(swigCPtr, this, Order.getCPtr(order), order);
  }

  public void enableLogging(LogLevel level) {
    ContextModeuleJNI.Context_enableLogging__SWIG_0(swigCPtr, this, level.swigValue());
  }

  public void enableLogging() {
    ContextModeuleJNI.Context_enableLogging__SWIG_1(swigCPtr, this);
  }

  public void subscribe(Instrument t) {
    ContextModeuleJNI.Context_subscribe(swigCPtr, this, Instrument.getCPtr(t), t);
  }

  public void unsubscribe(Instrument t) {
    ContextModeuleJNI.Context_unsubscribe(swigCPtr, this, Instrument.getCPtr(t), t);
  }

  public void loadInstrument(String s) {
    ContextModeuleJNI.Context_loadInstrument(swigCPtr, this, s);
  }

  public Instrument getInstrument(String t) {
    long cPtr = ContextModeuleJNI.Context_getInstrument(swigCPtr, this, t);
    return (cPtr == 0) ? null : new Instrument(cPtr, false);
  }

  public static Context getInstance() {
    long cPtr = ContextModeuleJNI.Context_getInstance();
    return (cPtr == 0) ? null : new Context(cPtr, false);
  }

  public SWIGTYPE_p_mutrade__detail__ContextImpl getContextImpl() {
    long cPtr = ContextModeuleJNI.Context_getContextImpl(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mutrade__detail__ContextImpl(cPtr, false);
  }

  public Application getApplication() {
    long cPtr = ContextModeuleJNI.Context_getApplication(swigCPtr, this);
    return (cPtr == 0) ? null : new Application(cPtr, false);
  }

  public void setApplication(Application arg0) {
    ContextModeuleJNI.Context_setApplication(swigCPtr, this, Application.getCPtr(arg0), arg0);
  }

}
