/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ExecutionResponse {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExecutionResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExecutionResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_ExecutionResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ExecutionResponse() {
    this(ContextModeuleJNI.new_ExecutionResponse__SWIG_0(), true);
  }

  public ExecutionResponse(String buf) {
    this(ContextModeuleJNI.new_ExecutionResponse__SWIG_1(buf), true);
  }

  public void dump() {
    ContextModeuleJNI.ExecutionResponse_dump(swigCPtr, this);
  }

  public java.math.BigInteger getClOrderId() {
    return ContextModeuleJNI.ExecutionResponse_getClOrderId(swigCPtr, this);
  }

  public short getTransactionType() {
    return ContextModeuleJNI.ExecutionResponse_getTransactionType(swigCPtr, this);
  }

  public short getResponseType() {
    return ContextModeuleJNI.ExecutionResponse_getResponseType(swigCPtr, this);
  }

  public long getTokenId() {
    return ContextModeuleJNI.ExecutionResponse_getTokenId(swigCPtr, this);
  }

  public void setClOrderId(java.math.BigInteger clOrderId) {
    ContextModeuleJNI.ExecutionResponse_setClOrderId(swigCPtr, this, clOrderId);
  }

  public void setTransactionType(short transactionType) {
    ContextModeuleJNI.ExecutionResponse_setTransactionType(swigCPtr, this, transactionType);
  }

  public void setResponseType(short responseType) {
    ContextModeuleJNI.ExecutionResponse_setResponseType(swigCPtr, this, responseType);
  }

  public void setTokenId(long val) {
    ContextModeuleJNI.ExecutionResponse_setTokenId(swigCPtr, this, val);
  }

}
