/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ExecutionReport {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExecutionReport(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExecutionReport obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_ExecutionReport(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ExecutionReport() {
    this(ContextModeuleJNI.new_ExecutionReport__SWIG_0(), true);
  }

  public ExecutionReport(String buf) {
    this(ContextModeuleJNI.new_ExecutionReport__SWIG_1(buf), true);
  }

  public void initialize() {
    ContextModeuleJNI.ExecutionReport_initialize(swigCPtr, this);
  }

  public long getClOrderId() {
    return ContextModeuleJNI.ExecutionReport_getClOrderId(swigCPtr, this);
  }

  public long getExchangeOrderId() {
    return ContextModeuleJNI.ExecutionReport_getExchangeOrderId(swigCPtr, this);
  }

  public long getSymbolId() {
    return ContextModeuleJNI.ExecutionReport_getSymbolId(swigCPtr, this);
  }

  public int getLastFillQuantity() {
    return ContextModeuleJNI.ExecutionReport_getLastFillQuantity(swigCPtr, this);
  }

  public int getLastFillPrice() {
    return ContextModeuleJNI.ExecutionReport_getLastFillPrice(swigCPtr, this);
  }

  public int getExchangeEntryTime() {
    return ContextModeuleJNI.ExecutionReport_getExchangeEntryTime(swigCPtr, this);
  }

  public int getExchangeModifyTime() {
    return ContextModeuleJNI.ExecutionReport_getExchangeModifyTime(swigCPtr, this);
  }

  public int getStrategyId() {
    return ContextModeuleJNI.ExecutionReport_getStrategyId(swigCPtr, this);
  }

  public int getClientId() {
    return ContextModeuleJNI.ExecutionReport_getClientId(swigCPtr, this);
  }

  public int getLimitPrice() {
    return ContextModeuleJNI.ExecutionReport_getLimitPrice(swigCPtr, this);
  }

  public OrderStatus getOrderStatus() {
    return OrderStatus.swigToEnum(ContextModeuleJNI.ExecutionReport_getOrderStatus(swigCPtr, this));
  }

  public OrderMode getOrderMode() {
    return OrderMode.swigToEnum(ContextModeuleJNI.ExecutionReport_getOrderMode(swigCPtr, this));
  }

  public int getOrderQuantity() {
    return ContextModeuleJNI.ExecutionReport_getOrderQuantity(swigCPtr, this);
  }

  public int getOrderPrice() {
    return ContextModeuleJNI.ExecutionReport_getOrderPrice(swigCPtr, this);
  }

  public int getIOCCanceledQuantity() {
    return ContextModeuleJNI.ExecutionReport_getIOCCanceledQuantity(swigCPtr, this);
  }

  public long getOriginalClOrderId() {
    return ContextModeuleJNI.ExecutionReport_getOriginalClOrderId(swigCPtr, this);
  }

  public long getConfirmationTimeSeconds() {
    return ContextModeuleJNI.ExecutionReport_getConfirmationTimeSeconds(swigCPtr, this);
  }

  public long getConfirmationTimeMicroSeconds() {
    return ContextModeuleJNI.ExecutionReport_getConfirmationTimeMicroSeconds(swigCPtr, this);
  }

  public short getIsOffline() {
    return ContextModeuleJNI.ExecutionReport_getIsOffline(swigCPtr, this);
  }

  public long getSequenceNumber() {
    return ContextModeuleJNI.ExecutionReport_getSequenceNumber(swigCPtr, this);
  }

  public long getTradeId() {
    return ContextModeuleJNI.ExecutionReport_getTradeId(swigCPtr, this);
  }

  public int getErrorCode() {
    return ContextModeuleJNI.ExecutionReport_getErrorCode(swigCPtr, this);
  }

  public int getReasonText() {
    return ContextModeuleJNI.ExecutionReport_getReasonText(swigCPtr, this);
  }

  public short getUnknownOrder() {
    return ContextModeuleJNI.ExecutionReport_getUnknownOrder(swigCPtr, this);
  }

  public String getInstrumentName() {
    return ContextModeuleJNI.ExecutionReport_getInstrumentName(swigCPtr, this);
  }

  public void setClOrderId(long clOrderId) {
    ContextModeuleJNI.ExecutionReport_setClOrderId(swigCPtr, this, clOrderId);
  }

  public void setExchangeOrderId(long exchangeOrderId) {
    ContextModeuleJNI.ExecutionReport_setExchangeOrderId(swigCPtr, this, exchangeOrderId);
  }

  public void setSymbolId(long symbolId) {
    ContextModeuleJNI.ExecutionReport_setSymbolId(swigCPtr, this, symbolId);
  }

  public void setLastFillQuantity(int qty) {
    ContextModeuleJNI.ExecutionReport_setLastFillQuantity(swigCPtr, this, qty);
  }

  public void setLastFillPrice(int price) {
    ContextModeuleJNI.ExecutionReport_setLastFillPrice(swigCPtr, this, price);
  }

  public void setExchangeEntryTime(int exchangeEntryTime) {
    ContextModeuleJNI.ExecutionReport_setExchangeEntryTime(swigCPtr, this, exchangeEntryTime);
  }

  public void setExchangeModifyTime(int exchangeModifyTime) {
    ContextModeuleJNI.ExecutionReport_setExchangeModifyTime(swigCPtr, this, exchangeModifyTime);
  }

  public void setStrategyId(int strategyId) {
    ContextModeuleJNI.ExecutionReport_setStrategyId(swigCPtr, this, strategyId);
  }

  public void setClientId(int clientId) {
    ContextModeuleJNI.ExecutionReport_setClientId(swigCPtr, this, clientId);
  }

  public void setLimitPrice(int limitPrice) {
    ContextModeuleJNI.ExecutionReport_setLimitPrice(swigCPtr, this, limitPrice);
  }

  public void setOrderStatus(OrderStatus orderStatus) {
    ContextModeuleJNI.ExecutionReport_setOrderStatus(swigCPtr, this, orderStatus.swigValue());
  }

  public void setOrderMode(OrderMode orderMode) {
    ContextModeuleJNI.ExecutionReport_setOrderMode(swigCPtr, this, orderMode.swigValue());
  }

  public void setOrderQuantity(int quantity) {
    ContextModeuleJNI.ExecutionReport_setOrderQuantity(swigCPtr, this, quantity);
  }

  public void setOrderPrice(int price) {
    ContextModeuleJNI.ExecutionReport_setOrderPrice(swigCPtr, this, price);
  }

  public void setIOCCanceledQuantity(int quantity) {
    ContextModeuleJNI.ExecutionReport_setIOCCanceledQuantity(swigCPtr, this, quantity);
  }

  public void setOriginalClOrderId(long originalClOrderId) {
    ContextModeuleJNI.ExecutionReport_setOriginalClOrderId(swigCPtr, this, originalClOrderId);
  }

  public void setConfirmationTimeSeconds(long seconds) {
    ContextModeuleJNI.ExecutionReport_setConfirmationTimeSeconds(swigCPtr, this, seconds);
  }

  public void setConfirmationTimeMicroSeconds(long microSeconds) {
    ContextModeuleJNI.ExecutionReport_setConfirmationTimeMicroSeconds(swigCPtr, this, microSeconds);
  }

  public void setIsOffline(short isOffline) {
    ContextModeuleJNI.ExecutionReport_setIsOffline(swigCPtr, this, isOffline);
  }

  public void setSequenceNumber(long sequenceNumber) {
    ContextModeuleJNI.ExecutionReport_setSequenceNumber(swigCPtr, this, sequenceNumber);
  }

  public void setTradeId(long tradeId) {
    ContextModeuleJNI.ExecutionReport_setTradeId(swigCPtr, this, tradeId);
  }

  public void setErrorCode(int errorCode) {
    ContextModeuleJNI.ExecutionReport_setErrorCode(swigCPtr, this, errorCode);
  }

  public void setReasonText(int reasonText) {
    ContextModeuleJNI.ExecutionReport_setReasonText(swigCPtr, this, reasonText);
  }

  public void setUnknownOrder(short unknownOrder) {
    ContextModeuleJNI.ExecutionReport_setUnknownOrder(swigCPtr, this, unknownOrder);
  }

  public void setInstrumentName(String instrumentName) {
    ContextModeuleJNI.ExecutionReport_setInstrumentName(swigCPtr, this, instrumentName);
  }

  public void dump() {
    ContextModeuleJNI.ExecutionReport_dump(swigCPtr, this);
  }

  public void dumpCSV(SWIGTYPE_p_std__ofstream csvFile) {
    ContextModeuleJNI.ExecutionReport_dumpCSV(swigCPtr, this, SWIGTYPE_p_std__ofstream.getCPtr(csvFile));
  }

  public int serialize(String buf) {
    return ContextModeuleJNI.ExecutionReport_serialize(swigCPtr, this, buf);
  }

}
