/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class InstrumentType {
  public final static InstrumentType InstrumentType_STOCK = new InstrumentType("InstrumentType_STOCK");
  public final static InstrumentType InstrumentType_FUTURE = new InstrumentType("InstrumentType_FUTURE");
  public final static InstrumentType InstrumentType_OPTION = new InstrumentType("InstrumentType_OPTION");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static InstrumentType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + InstrumentType.class + " with value " + swigValue);
  }

  private InstrumentType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private InstrumentType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private InstrumentType(String swigName, InstrumentType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static InstrumentType[] swigValues = { InstrumentType_STOCK, InstrumentType_FUTURE, InstrumentType_OPTION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

