/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Instrument {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Instrument(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Instrument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Instrument(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Instrument() {
    this(ContextModeuleJNI.new_Instrument__SWIG_0(), true);
  }

  public Instrument(String identifier) {
    this(ContextModeuleJNI.new_Instrument__SWIG_1(identifier), true);
  }

  public InstrumentType getInstrumentType() {
    return InstrumentType.swigToEnum(ContextModeuleJNI.Instrument_getInstrumentType(swigCPtr, this));
  }

  public long getStrikePrice() {
    return ContextModeuleJNI.Instrument_getStrikePrice(swigCPtr, this);
  }

  public String getSeries() {
    return ContextModeuleJNI.Instrument_getSeries(swigCPtr, this);
  }

  public int getLotSize() {
    return ContextModeuleJNI.Instrument_getLotSize(swigCPtr, this);
  }

  public int getTickSize() {
    return ContextModeuleJNI.Instrument_getTickSize(swigCPtr, this);
  }

  public OptionType getOptionType() {
    return OptionType.swigToEnum(ContextModeuleJNI.Instrument_getOptionType(swigCPtr, this));
  }

  public String getInstrumentName() {
    return ContextModeuleJNI.Instrument_getInstrumentName(swigCPtr, this);
  }

}
