/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Logger {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Logger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Logger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Logger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Logger getInstance() {
    long cPtr = ContextModeuleJNI.Logger_getInstance();
    return (cPtr == 0) ? null : new Logger(cPtr, false);
  }

  public void setLogLevel(LogLevel level) {
    ContextModeuleJNI.Logger_setLogLevel(swigCPtr, this, level.swigValue());
  }

  public void log(LogLevel level, String message) {
    ContextModeuleJNI.Logger_log(swigCPtr, this, level.swigValue(), message);
  }

}
