/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class LogLevel {
  public final static LogLevel INFO = new LogLevel("INFO");
  public final static LogLevel WARN = new LogLevel("WARN");
  public final static LogLevel ERROR_ = new LogLevel("ERROR_");
  public final static LogLevel FATAL = new LogLevel("FATAL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LogLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LogLevel.class + " with value " + swigValue);
  }

  private LogLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LogLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LogLevel(String swigName, LogLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LogLevel[] swigValues = { INFO, WARN, ERROR_, FATAL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

