/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MarketData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MarketData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MarketData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_MarketData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MarketData() {
    this(ContextModeuleJNI.new_MarketData__SWIG_0(), true);
  }

  public MarketData(Quote arg0) {
    this(ContextModeuleJNI.new_MarketData__SWIG_1(Quote.getCPtr(arg0), arg0), true);
  }

  public Instrument getInstrument() {
    return new Instrument(ContextModeuleJNI.MarketData_getInstrument(swigCPtr, this), true);
  }

  public int getLastPrice() {
    return ContextModeuleJNI.MarketData_getLastPrice(swigCPtr, this);
  }

  public int getLastQty() {
    return ContextModeuleJNI.MarketData_getLastQty(swigCPtr, this);
  }

  public int getLastTime() {
    return ContextModeuleJNI.MarketData_getLastTime(swigCPtr, this);
  }

  public int getTotalQty() {
    return ContextModeuleJNI.MarketData_getTotalQty(swigCPtr, this);
  }

  public int getDepth(Side side) {
    return ContextModeuleJNI.MarketData_getDepth(swigCPtr, this, side.swigValue());
  }

  public int getPrice(Side side, int rank) {
    return ContextModeuleJNI.MarketData_getPrice(swigCPtr, this, side.swigValue(), rank);
  }

  public int getQty(Side side, int rank) {
    return ContextModeuleJNI.MarketData_getQty(swigCPtr, this, side.swigValue(), rank);
  }

  public int getRank(Side side, int price) {
    return ContextModeuleJNI.MarketData_getRank(swigCPtr, this, side.swigValue(), price);
  }

  public boolean getCount(Side side, int rank) {
    return ContextModeuleJNI.MarketData_getCount(swigCPtr, this, side.swigValue(), rank);
  }

  public boolean hasQty(Side side, int qty) {
    return ContextModeuleJNI.MarketData_hasQty(swigCPtr, this, side.swigValue(), qty);
  }

  public int getAvgPrice(Side side, int qty) {
    return ContextModeuleJNI.MarketData_getAvgPrice(swigCPtr, this, side.swigValue(), qty);
  }

  public int getQtyForAvgPrice(Side side, int avgPrice) {
    return ContextModeuleJNI.MarketData_getQtyForAvgPrice(swigCPtr, this, side.swigValue(), avgPrice);
  }

  public int getAvgPriceForQty(Side side, int qty) {
    return ContextModeuleJNI.MarketData_getAvgPriceForQty(swigCPtr, this, side.swigValue(), qty);
  }

  public int getQtyForWorstPrice(Side side, int worstPrice) {
    return ContextModeuleJNI.MarketData_getQtyForWorstPrice(swigCPtr, this, side.swigValue(), worstPrice);
  }

  public int getWorstPriceForQty(Side side, int qty) {
    return ContextModeuleJNI.MarketData_getWorstPriceForQty(swigCPtr, this, side.swigValue(), qty);
  }

  public int getDayOpen() {
    return ContextModeuleJNI.MarketData_getDayOpen(swigCPtr, this);
  }

  public int getDayHigh() {
    return ContextModeuleJNI.MarketData_getDayHigh(swigCPtr, this);
  }

  public int getDayLow() {
    return ContextModeuleJNI.MarketData_getDayLow(swigCPtr, this);
  }

  public int getDayClose() {
    return ContextModeuleJNI.MarketData_getDayClose(swigCPtr, this);
  }

}
