/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class OptionType {
  public final static OptionType OptionType_PUT = new OptionType("OptionType_PUT");
  public final static OptionType OptionType_CALL = new OptionType("OptionType_CALL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OptionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OptionType.class + " with value " + swigValue);
  }

  private OptionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OptionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OptionType(String swigName, OptionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OptionType[] swigValues = { OptionType_PUT, OptionType_CALL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

