/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class OrderStatus {
  public final static OrderStatus OrderStatus_PENDING = new OrderStatus("OrderStatus_PENDING");
  public final static OrderStatus OrderStatus_CONFIRMED = new OrderStatus("OrderStatus_CONFIRMED");
  public final static OrderStatus OrderStatus_FILLED = new OrderStatus("OrderStatus_FILLED");
  public final static OrderStatus OrderStatus_CANCELED = new OrderStatus("OrderStatus_CANCELED");
  public final static OrderStatus OrderStatus_REPLACED = new OrderStatus("OrderStatus_REPLACED");
  public final static OrderStatus OrderStatus_NEW_REJECTED = new OrderStatus("OrderStatus_NEW_REJECTED");
  public final static OrderStatus OrderStatus_CANCEL_REJECTED = new OrderStatus("OrderStatus_CANCEL_REJECTED");
  public final static OrderStatus OrderStatus_REPLACE_REJECTED = new OrderStatus("OrderStatus_REPLACE_REJECTED");
  public final static OrderStatus OrderStatus_FROZEN = new OrderStatus("OrderStatus_FROZEN");
  public final static OrderStatus OrderStatus_MARKET_TO_LIMIT = new OrderStatus("OrderStatus_MARKET_TO_LIMIT");
  public final static OrderStatus OrderStatus_TRIGGERED = new OrderStatus("OrderStatus_TRIGGERED");
  public final static OrderStatus OrderStatus_PARTIALLY_FILLED = new OrderStatus("OrderStatus_PARTIALLY_FILLED");
  public final static OrderStatus OrderStatus_CANCELED_OF_IOC = new OrderStatus("OrderStatus_CANCELED_OF_IOC");
  public final static OrderStatus OrderStatus_RMS_REJECT = new OrderStatus("OrderStatus_RMS_REJECT");
  public final static OrderStatus OrderStatus_MAX = new OrderStatus("OrderStatus_MAX");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrderStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrderStatus.class + " with value " + swigValue);
  }

  private OrderStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrderStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrderStatus(String swigName, OrderStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrderStatus[] swigValues = { OrderStatus_PENDING, OrderStatus_CONFIRMED, OrderStatus_FILLED, OrderStatus_CANCELED, OrderStatus_REPLACED, OrderStatus_NEW_REJECTED, OrderStatus_CANCEL_REJECTED, OrderStatus_REPLACE_REJECTED, OrderStatus_FROZEN, OrderStatus_MARKET_TO_LIMIT, OrderStatus_TRIGGERED, OrderStatus_PARTIALLY_FILLED, OrderStatus_CANCELED_OF_IOC, OrderStatus_RMS_REJECT, OrderStatus_MAX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

