/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class OrderMode {
  public final static OrderMode OrderMode_BUY = new OrderMode("OrderMode_BUY", 0);
  public final static OrderMode OrderMode_SELL = new OrderMode("OrderMode_SELL", 1);
  public final static OrderMode OrderMode_MAX = new OrderMode("OrderMode_MAX");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrderMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrderMode.class + " with value " + swigValue);
  }

  private OrderMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrderMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrderMode(String swigName, OrderMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrderMode[] swigValues = { OrderMode_BUY, OrderMode_SELL, OrderMode_MAX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

