/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Order {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Order(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Order obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Order(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Order() {
    this(ContextModeuleJNI.new_Order(), true);
  }

  public int getClientId() {
    return ContextModeuleJNI.Order_getClientId(swigCPtr, this);
  }

  public TransactionType getTransactionType() {
    return TransactionType.swigToEnum(ContextModeuleJNI.Order_getTransactionType(swigCPtr, this));
  }

  public long getClOrdId() {
    return ContextModeuleJNI.Order_getClOrdId(swigCPtr, this);
  }

  public long getOrigClOrdId() {
    return ContextModeuleJNI.Order_getOrigClOrdId(swigCPtr, this);
  }

  public String getExchangeOrderId() {
    return ContextModeuleJNI.Order_getExchangeOrderId(swigCPtr, this);
  }

  public String getSymbol() {
    return ContextModeuleJNI.Order_getSymbol(swigCPtr, this);
  }

  public Side getOrderMode() {
    return Side.swigToEnum(ContextModeuleJNI.Order_getOrderMode(swigCPtr, this));
  }

  public int getQuantity() {
    return ContextModeuleJNI.Order_getQuantity(swigCPtr, this);
  }

  public int getDisclosedQuantity() {
    return ContextModeuleJNI.Order_getDisclosedQuantity(swigCPtr, this);
  }

  public int getFilledQuantity() {
    return ContextModeuleJNI.Order_getFilledQuantity(swigCPtr, this);
  }

  public int getOldQuantity() {
    return ContextModeuleJNI.Order_getOldQuantity(swigCPtr, this);
  }

  public int getPrice() {
    return ContextModeuleJNI.Order_getPrice(swigCPtr, this);
  }

  public int getStopPrice() {
    return ContextModeuleJNI.Order_getStopPrice(swigCPtr, this);
  }

  public InstrumentType getSecurityType() {
    return InstrumentType.swigToEnum(ContextModeuleJNI.Order_getSecurityType(swigCPtr, this));
  }

  public TimeInForce getOrderValidity() {
    return TimeInForce.swigToEnum(ContextModeuleJNI.Order_getOrderValidity(swigCPtr, this));
  }

  public OrderType getOrderType() {
    return OrderType.swigToEnum(ContextModeuleJNI.Order_getOrderType(swigCPtr, this));
  }

  public OrderStatus getOrderStatus() {
    return OrderStatus.swigToEnum(ContextModeuleJNI.Order_getOrderStatus(swigCPtr, this));
  }

  public int getExchangeEntryTime() {
    return ContextModeuleJNI.Order_getExchangeEntryTime(swigCPtr, this);
  }

  public int getExchangeModifyTime() {
    return ContextModeuleJNI.Order_getExchangeModifyTime(swigCPtr, this);
  }

  public void setClientId(int val) {
    ContextModeuleJNI.Order_setClientId(swigCPtr, this, val);
  }

  public void setTransactionType(TransactionType val) {
    ContextModeuleJNI.Order_setTransactionType(swigCPtr, this, val.swigValue());
  }

  public void setClOrdId(long val) {
    ContextModeuleJNI.Order_setClOrdId(swigCPtr, this, val);
  }

  public void setOrigClOrdId(long val) {
    ContextModeuleJNI.Order_setOrigClOrdId(swigCPtr, this, val);
  }

  public void setExchangeOrderId(String val) {
    ContextModeuleJNI.Order_setExchangeOrderId(swigCPtr, this, val);
  }

  public void setSymbol(String val) {
    ContextModeuleJNI.Order_setSymbol(swigCPtr, this, val);
  }

  public void setOrderMode(Side val) {
    ContextModeuleJNI.Order_setOrderMode(swigCPtr, this, val.swigValue());
  }

  public void setQuantity(int val) {
    ContextModeuleJNI.Order_setQuantity(swigCPtr, this, val);
  }

  public void setDisclosedQuantity(int val) {
    ContextModeuleJNI.Order_setDisclosedQuantity(swigCPtr, this, val);
  }

  public void setFilledQuantity(int val) {
    ContextModeuleJNI.Order_setFilledQuantity(swigCPtr, this, val);
  }

  public void setOldQuantity(int val) {
    ContextModeuleJNI.Order_setOldQuantity(swigCPtr, this, val);
  }

  public void setPrice(int val) {
    ContextModeuleJNI.Order_setPrice(swigCPtr, this, val);
  }

  public void setStopPrice(int val) {
    ContextModeuleJNI.Order_setStopPrice(swigCPtr, this, val);
  }

  public void setSecurityType(InstrumentType val) {
    ContextModeuleJNI.Order_setSecurityType(swigCPtr, this, val.swigValue());
  }

  public void setOrderValidity(TimeInForce val) {
    ContextModeuleJNI.Order_setOrderValidity(swigCPtr, this, val.swigValue());
  }

  public void setOrderType(OrderType val) {
    ContextModeuleJNI.Order_setOrderType(swigCPtr, this, val.swigValue());
  }

  public void setOrderStatus(OrderStatus val) {
    ContextModeuleJNI.Order_setOrderStatus(swigCPtr, this, val.swigValue());
  }

  public void setExchangeEntryTime(int val) {
    ContextModeuleJNI.Order_setExchangeEntryTime(swigCPtr, this, val);
  }

  public void setExchangeModifyTime(int val) {
    ContextModeuleJNI.Order_setExchangeModifyTime(swigCPtr, this, val);
  }

  public void initialize() {
    ContextModeuleJNI.Order_initialize(swigCPtr, this);
  }

  public void dumpOrder() {
    ContextModeuleJNI.Order_dumpOrder(swigCPtr, this);
  }

}
