/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Portfolio {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Portfolio(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Portfolio obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Portfolio(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Portfolio getInstance() {
    long cPtr = ContextModeuleJNI.Portfolio_getInstance();
    return (cPtr == 0) ? null : new Portfolio(cPtr, false);
  }

  public void insert(Order order) {
    ContextModeuleJNI.Portfolio_insert(swigCPtr, this, Order.getCPtr(order), order);
  }

  public Order getOrderByTokenId(int tokenId) {
    long cPtr = ContextModeuleJNI.Portfolio_getOrderByTokenId(swigCPtr, this, tokenId);
    return (cPtr == 0) ? null : new Order(cPtr, false);
  }

  public NetPositions getNetPositions() {
    return new NetPositions(ContextModeuleJNI.Portfolio_getNetPositions(swigCPtr, this), false);
  }

  public OrderBook getOrderBook() {
    return new OrderBook(ContextModeuleJNI.Portfolio_getOrderBook(swigCPtr, this), false);
  }

  public TradeBook getTradeBook() {
    return new TradeBook(ContextModeuleJNI.Portfolio_getTradeBook(swigCPtr, this), false);
  }

}
