/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Position {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Position(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Position obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Position(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Position(Instrument instrument) {
    this(ContextModeuleJNI.new_Position__SWIG_0(Instrument.getCPtr(instrument), instrument), true);
  }

  public Position(Position arg0) {
    this(ContextModeuleJNI.new_Position__SWIG_1(Position.getCPtr(arg0), arg0), true);
  }

  public void initialize() {
    ContextModeuleJNI.Position_initialize(swigCPtr, this);
  }

  public int getQuantity() {
    return ContextModeuleJNI.Position_getQuantity(swigCPtr, this);
  }

  public int getAveragePrice() {
    return ContextModeuleJNI.Position_getAveragePrice(swigCPtr, this);
  }

  public Instrument getInstrument() {
    return new Instrument(ContextModeuleJNI.Position_getInstrument(swigCPtr, this), true);
  }

  public Side getOrderMode() {
    return Side.swigToEnum(ContextModeuleJNI.Position_getOrderMode(swigCPtr, this));
  }

  public void setQuantity(int val) {
    ContextModeuleJNI.Position_setQuantity(swigCPtr, this, val);
  }

  public void setAveragePrice(int val) {
    ContextModeuleJNI.Position_setAveragePrice(swigCPtr, this, val);
  }

  public void setInstrument(Instrument val) {
    ContextModeuleJNI.Position_setInstrument(swigCPtr, this, Instrument.getCPtr(val), val);
  }

  public void setOrderType(Side val) {
    ContextModeuleJNI.Position_setOrderType(swigCPtr, this, val.swigValue());
  }

}
