/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Quote {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Quote(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Quote obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Quote(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Quote() {
    this(ContextModeuleJNI.new_Quote__SWIG_0(), true);
  }

  public Quote(Quote arg0) {
    this(ContextModeuleJNI.new_Quote__SWIG_1(Quote.getCPtr(arg0), arg0), true);
  }

  public void setSymbolId(long val) {
    ContextModeuleJNI.Quote_setSymbolId(swigCPtr, this, val);
  }

  public void setNummberOfTrades(long val) {
    ContextModeuleJNI.Quote_setNummberOfTrades(swigCPtr, this, val);
  }

  public void setVolume(long val) {
    ContextModeuleJNI.Quote_setVolume(swigCPtr, this, val);
  }

  public void setValue(long val) {
    ContextModeuleJNI.Quote_setValue(swigCPtr, this, val);
  }

  public void setLastTradePrice(long val) {
    ContextModeuleJNI.Quote_setLastTradePrice(swigCPtr, this, val);
  }

  public void setLastTradeQty(long val) {
    ContextModeuleJNI.Quote_setLastTradeQty(swigCPtr, this, val);
  }

  public void setOpenPrice(long val) {
    ContextModeuleJNI.Quote_setOpenPrice(swigCPtr, this, val);
  }

  public void setClosePrice(long val) {
    ContextModeuleJNI.Quote_setClosePrice(swigCPtr, this, val);
  }

  public void setHighPrice(long val) {
    ContextModeuleJNI.Quote_setHighPrice(swigCPtr, this, val);
  }

  public void setLowPrice(long val) {
    ContextModeuleJNI.Quote_setLowPrice(swigCPtr, this, val);
  }

  public void setTotalBidQty(long val) {
    ContextModeuleJNI.Quote_setTotalBidQty(swigCPtr, this, val);
  }

  public void setTotalAskQty(long val) {
    ContextModeuleJNI.Quote_setTotalAskQty(swigCPtr, this, val);
  }

  public void setLowerCktLimit(long val) {
    ContextModeuleJNI.Quote_setLowerCktLimit(swigCPtr, this, val);
  }

  public void setUpperCktLimit(long val) {
    ContextModeuleJNI.Quote_setUpperCktLimit(swigCPtr, this, val);
  }

  public void setDepth(short val) {
    ContextModeuleJNI.Quote_setDepth(swigCPtr, this, val);
  }

  public void setBidPrice(SWIGTYPE_p_long_long val) {
    ContextModeuleJNI.Quote_setBidPrice(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(val));
  }

  public void setBidQty(SWIGTYPE_p_long_long val) {
    ContextModeuleJNI.Quote_setBidQty(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(val));
  }

  public void setAskPrice(SWIGTYPE_p_long_long val) {
    ContextModeuleJNI.Quote_setAskPrice(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(val));
  }

  public void setAskQty(SWIGTYPE_p_long_long val) {
    ContextModeuleJNI.Quote_setAskQty(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(val));
  }

  public long getSymbolId() {
    return ContextModeuleJNI.Quote_getSymbolId(swigCPtr, this);
  }

  public long getNumberOfTrades() {
    return ContextModeuleJNI.Quote_getNumberOfTrades(swigCPtr, this);
  }

  public long getVolume() {
    return ContextModeuleJNI.Quote_getVolume(swigCPtr, this);
  }

  public long getValue() {
    return ContextModeuleJNI.Quote_getValue(swigCPtr, this);
  }

  public long getLastTradePrice() {
    return ContextModeuleJNI.Quote_getLastTradePrice(swigCPtr, this);
  }

  public long getLastTradeQty() {
    return ContextModeuleJNI.Quote_getLastTradeQty(swigCPtr, this);
  }

  public long getOpenPrice() {
    return ContextModeuleJNI.Quote_getOpenPrice(swigCPtr, this);
  }

  public long getClosePrice() {
    return ContextModeuleJNI.Quote_getClosePrice(swigCPtr, this);
  }

  public long getHighPrice() {
    return ContextModeuleJNI.Quote_getHighPrice(swigCPtr, this);
  }

  public long getLowPrice() {
    return ContextModeuleJNI.Quote_getLowPrice(swigCPtr, this);
  }

  public long getTotalBidQty() {
    return ContextModeuleJNI.Quote_getTotalBidQty(swigCPtr, this);
  }

  public long getTotalAskQty() {
    return ContextModeuleJNI.Quote_getTotalAskQty(swigCPtr, this);
  }

  public long getLowerCktLimit() {
    return ContextModeuleJNI.Quote_getLowerCktLimit(swigCPtr, this);
  }

  public long getUpperCktLimit() {
    return ContextModeuleJNI.Quote_getUpperCktLimit(swigCPtr, this);
  }

  public short getDepth() {
    return ContextModeuleJNI.Quote_getDepth(swigCPtr, this);
  }

  public SWIGTYPE_p_long_long getBidPrice() {
    long cPtr = ContextModeuleJNI.Quote_getBidPrice(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

  public SWIGTYPE_p_long_long getBidQty() {
    long cPtr = ContextModeuleJNI.Quote_getBidQty(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

  public SWIGTYPE_p_long_long getAskPrice() {
    long cPtr = ContextModeuleJNI.Quote_getAskPrice(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

  public SWIGTYPE_p_long_long getAskQty() {
    long cPtr = ContextModeuleJNI.Quote_getAskQty(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

}
