/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class Side {
  public final static Side Side_BUY = new Side("Side_BUY", 0);
  public final static Side Side_SELL = new Side("Side_SELL", 1);
  public final static Side Side_BID = new Side("Side_BID", 0);
  public final static Side Side_ASK = new Side("Side_ASK", 1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Side swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Side.class + " with value " + swigValue);
  }

  private Side(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Side(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Side(String swigName, Side swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Side[] swigValues = { Side_BUY, Side_SELL, Side_BID, Side_ASK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

