/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Trade {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Trade(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Trade obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ContextModeuleJNI.delete_Trade(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Trade(Instrument arg0) {
    this(ContextModeuleJNI.new_Trade__SWIG_0(Instrument.getCPtr(arg0), arg0), true);
  }

  public Trade(Trade arg0) {
    this(ContextModeuleJNI.new_Trade__SWIG_1(Trade.getCPtr(arg0), arg0), true);
  }

  public void initialize() {
    ContextModeuleJNI.Trade_initialize(swigCPtr, this);
  }

  public Instrument getInstrument() {
    return new Instrument(ContextModeuleJNI.Trade_getInstrument(swigCPtr, this), true);
  }

  public long getTradeId() {
    return ContextModeuleJNI.Trade_getTradeId(swigCPtr, this);
  }

  public long getClOrdId() {
    return ContextModeuleJNI.Trade_getClOrdId(swigCPtr, this);
  }

  public long getOrigClOrdId() {
    return ContextModeuleJNI.Trade_getOrigClOrdId(swigCPtr, this);
  }

  public long getExchangeOrderId() {
    return ContextModeuleJNI.Trade_getExchangeOrderId(swigCPtr, this);
  }

  public Side getOrderMode() {
    return Side.swigToEnum(ContextModeuleJNI.Trade_getOrderMode(swigCPtr, this));
  }

  public int getFilledQuantity() {
    return ContextModeuleJNI.Trade_getFilledQuantity(swigCPtr, this);
  }

  public int getFilledPrice() {
    return ContextModeuleJNI.Trade_getFilledPrice(swigCPtr, this);
  }

  public OrderType getOrderType() {
    return OrderType.swigToEnum(ContextModeuleJNI.Trade_getOrderType(swigCPtr, this));
  }

  public int getTradeTime() {
    return ContextModeuleJNI.Trade_getTradeTime(swigCPtr, this);
  }

  public void setInstrument(Instrument val) {
    ContextModeuleJNI.Trade_setInstrument(swigCPtr, this, Instrument.getCPtr(val), val);
  }

  public void setTradeId(long val) {
    ContextModeuleJNI.Trade_setTradeId(swigCPtr, this, val);
  }

  public void setClOrdId(long val) {
    ContextModeuleJNI.Trade_setClOrdId(swigCPtr, this, val);
  }

  public void setOrigClOrdId(long val) {
    ContextModeuleJNI.Trade_setOrigClOrdId(swigCPtr, this, val);
  }

  public void setExchangeOrderId(long val) {
    ContextModeuleJNI.Trade_setExchangeOrderId(swigCPtr, this, val);
  }

  public void setOrderMode(Side val) {
    ContextModeuleJNI.Trade_setOrderMode(swigCPtr, this, val.swigValue());
  }

  public void setFilledQuantity(int val) {
    ContextModeuleJNI.Trade_setFilledQuantity(swigCPtr, this, val);
  }

  public void setFilledPrice(int val) {
    ContextModeuleJNI.Trade_setFilledPrice(swigCPtr, this, val);
  }

  public void setOrderType(OrderType val) {
    ContextModeuleJNI.Trade_setOrderType(swigCPtr, this, val.swigValue());
  }

  public void setTradeTime(int val) {
    ContextModeuleJNI.Trade_setTradeTime(swigCPtr, this, val);
  }

}
