/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class TransactionType {
  public final static TransactionType TransactionType_NEW = new TransactionType("TransactionType_NEW");
  public final static TransactionType TransactionType_MODIFY = new TransactionType("TransactionType_MODIFY");
  public final static TransactionType TransactionType_CANCEL = new TransactionType("TransactionType_CANCEL");
  public final static TransactionType TransactionType_MAX = new TransactionType("TransactionType_MAX");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TransactionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TransactionType.class + " with value " + swigValue);
  }

  private TransactionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TransactionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TransactionType(String swigName, TransactionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TransactionType[] swigValues = { TransactionType_NEW, TransactionType_MODIFY, TransactionType_CANCEL, TransactionType_MAX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

